### ISSUE TITLE
./src/emitter no longer exists

### ISSUE THREAD

**Issue by rekkisomo** [NicolasSiver/nodebb-plugin-ns-custom-fields#25]
This plugin no longer loads when nodebb is starting, and gives the following error:
`2018-12-18T17:11:56.526Z [4567/25413] - error: Error: Cannot find module './src/emitter'`
inside the `nodebb.js` file.

**Comment by rekkisomo** [comment]
Discovered fix, #26

**Comment by NicolasSiver** [comment]
The plugin was configured to work with v1.5 and _higher_. It was a matter of time when NodeBB will introduce a breaking minor version.

**Comment by NicolasSiver** [comment]
I'm going to do extra small changes and release the compatible version with NodeBB v1.11.x
